swiftyfinch/Rugby

- .github/workflows/regress.yml
- .gitignore
- README.md
- TestProject/Fastlane/Fastfile
- TestProject/Fastlane/Tests/Commands/Cache
- TestProject/Fastlane/Tests/Commands/Drop
- TestProject/Fastlane/Tests/Commands/Focus
- TestProject/Fastlane/Tests/Commands/Plans
- TestProject/Fastlane/Xcode
The main goal is to reduce ci workflow complexity.
> 🧼Move e2e tests to fastlane.

- Sources/rugby/Commands/Cache/Command/CacheHeader.swift
- Sources/rugby/Commands/Cache/Steps/Prepare/Substeps/SelectPods.swift
- Sources/rugby/Commands/Plan/Command/PlanHeader.swift
- Sources/rugby/Commands/Plan/Parser/DecodableModels/CacheDecodable.swift
> 🚧 (Beta) Add `--include` option for Cache command.

- Sources/Rugby/Commands/Cache/Other/Build/LogFormatter.swift
- Sources/Rugby/Commands/Cache/Other/Build/XcodeBuild.swift
- Sources/Rugby/Commands/Cache/Other/Build/XcodeBuildRunner.swift
- Sources/Rugby/Commands/Cache/Other/Errors/CacheError.swift
- Sources/Rugby/Commands/Cache/Steps/CacheBuildStep.swift
- Sources/Rugby/Common/LogPrinter/Extensions/Printer+Spinner.swift
- Sources/Rugby/Common/Progress/Progress.swift
> 🐛 Show errors on Xcode build failed

- Sources/Rugby/Commands/Cache/Other/Errors/CacheError.swift
- Sources/Rugby/Commands/Doctor/Doctor.swift
- Sources/Rugby/Common/Utils/WrapError.swift
Now you will get the suggestion to call 🏈 Rugby doctor if you have any error:
> 🚑 Suggest call doctor

- Package.resolved
- Package.swift
- Sources/Rugby/Common/XcodeProj/Scheme/XcodeProj+RemoveSchemes.swift
> Update packages to build on Xcode13

- Docs/Cache.md
> Fix typo in Cache documentation (line 08)

- Sources/Rugby/Common/XcodeProj/Scheme/XcodeProj+RemoveSchemes.swift
Trim username whitespaces and newlines:
```shell
// echo ${USER}
swiftyfinch\n -> swiftyfinch
```
> 🐛 Fix scheme removing

- .github/workflows/regress.yml
- Docs/Cache.md
- Docs/Drop.md
- Docs/Focus.md
- Docs/Plans.md
- Sources/Rugby/Commands/Cache/Command/CacheHeader.swift
- Sources/Rugby/Commands/Cache/Command/CacheRun.swift
- Sources/Rugby/Commands/Cache/Other/Checksums/CacheManager.swift
- Sources/Rugby/Commands/Cache/Other/Errors/CacheError.swift
- Sources/Rugby/Commands/Cache/Steps/CacheBuildStep.swift
- Sources/Rugby/Commands/Cache/Steps/CacheIntegrateStep.swift
- Sources/Rugby/Commands/Cache/Steps/Prepare/CachePrepareStep.swift
- Sources/Rugby/Commands/Cache/Steps/Prepare/Substeps/FindBuildPods.swift
- Sources/Rugby/Commands/Plan/Parser/DecodableModels/CacheDecodable.swift
- Sources/Rugby/Commands/Plan/Subcommands/PlansExample.swift
- Sources/Rugby/Common/Environment/ARCH.swift
- Sources/Rugby/Common/Environment/SDK.swift
- Sources/Rugby/Common/Environment/String+Env.swift
- Sources/Rugby/Common/History/EnvironmentCollector.swift
- Sources/Rugby/Common/LogPrinter/Extensions/Printer+Spinner.swift
- Sources/Rugby/Common/LogPrinter/Printers/OneLinePrinter.swift
- TestProject/Fastlane/Tests/Commands/Cache
- TestProject/TestProject/TestProject.xcodeproj/xcshareddata/xcschemes/TestProject.xcscheme
- TestProject/TestProject/TestProject/AppDelegate.swift
> 🔭 Build both ios and sim SDKs

- Sources/Rugby/Commands/Doctor/Doctor.swift
I just decided to make 🏈 Rugby doctor more clearly.
None
> 🚑 Update Rugby doctor

- .github/workflows/regress.yml
- Sources/Rugby/Commands/Plan/Command/PlanRun.swift
I renamed `selectedPlan(plans)` method to `selectPlan(plans)` to add backward compatibility for Xcode 12.4.
Issue began in this [discussion](https://github.com/swiftyfinch/Rugby/discussions/107), then decision made by @swiftyfinch in this [comment](https://github.com/swiftyfinch/Rugby/discussions/107#discussioncomment-1988851), and a whole discussion opened for it [here](https://github.com/swiftyfinch/Rugby/discussions/115)
> Support installation for Xcode 12.4

- .github/workflows/regress.yml
> 🏈 Use Xcode 13 on ci

- Sources/Rugby/Commands/Cache/Other/Build/XcodeBuild.swift
- Sources/Rugby/Common/Extensions/String+File.swift
- TestProject/Fastlane/Tests/Commands/Cache
- TestProject/TestProject/TestProject.xcodeproj/project.pbxproj
- TestProject/TestProject/TestProject.xcodeproj/xcshareddata/xcschemes/TestLocalizable.xcscheme
Escape spaces in the config parameter
It's related to #119
> 🐛 Shell friendly config

- Sources/Rugby/Commands/Cache/Other/PatchConfigs/CacheIntegration.swift
- Sources/Rugby/Commands/Cache/Steps/CacheCleanupStep.swift
- Sources/Rugby/Commands/Cache/Steps/CacheIntegrateStep.swift
Fix wording _builded_ -> _built_.
[Archaic past of build](https://slovar-vocab.com/english/merriam-webster-vocabulary/builded-7165235.html).
> Fix wording

- Package.resolved
- Package.swift
- Sources/Rugby/Common/Utils/ShellRunner.swift
- Sources/Rugby/Common/Utils/WrapError.swift
**Before:**
**After:**
https://github.com/mxcl/LegibleError
> 🔭 Make errors more understandable

- Package.resolved
- Package.swift
- Sources/Rugby/Common/Extensions/Error+BeautifulError.swift
- Sources/Rugby/Common/Utils/ShellRunner.swift
- Sources/Rugby/Common/Utils/WrapError.swift
1. Fixed error description in some cases2;
2. Removed LegibleError dependency.
#155
> 🐛 Beautiful error

- Formula/rugby.rb
- Sources/Rugby/main.swift
> 🔭 Add distribution binary with Homebrew 🍺

- Docs/Cache.md
- Sources/Rugby/Commands/Cache/Command/CacheHeader.swift
- Sources/Rugby/Commands/Cache/Steps/CacheIntegrateStep.swift
- Sources/Rugby/Commands/Drop/PatchConfigs/DropCleanupConfigs.swift
- Sources/Rugby/Commands/Plan/Command/PlanHeader.swift
- Sources/Rugby/Commands/Plan/Parser/DecodableModels/CacheDecodable.swift
- Sources/Rugby/Common/Environment/String+Env.swift
- TestProject/Fastlane/Tests/Commands/Cache
Check out the linked issue for a description.
Closes #153 
> 🔭 Using relative paths

- Docs/Cache.md
- Docs/Drop.md
- Docs/Focus.md
- Docs/Plans.md
- Docs/README.md
- Sources/Rugby/Commands/Cache/Command/CacheHeader.swift
- Sources/Rugby/Commands/Cache/Other/Checksums/ChecksumsProvider.swift
- Sources/Rugby/Commands/Cache/Other/Checksums/CombinedChecksum.swift
- Sources/Rugby/Commands/Cache/Steps/CacheBuildStep.swift
- Sources/Rugby/Commands/Cache/Steps/Prepare/Substeps/FindBuildPods.swift
- Sources/Rugby/Commands/Plan/Command/PlanHeader.swift
- Sources/Rugby/Commands/Plan/Parser/DecodableModels/CacheDecodable.swift
- Sources/Rugby/Commands/Plan/Subcommands/PlansExample.swift
- Sources/Rugby/Commands/Rollback/Rollback.swift
- Sources/Rugby/Common/Command/Command.swift
- Sources/Rugby/Common/Command/CommonFlags.swift
Update all api and documentation after #181 #183
#181 #183
> 🔭 Update docs and api

- Sources/Rugby/Common/Utils/ShellRunner.swift
Add trimming whitespaces and isEmpty check for stderr value to avoid empty error message.
> Add trimming whitespaces and isEmpty check for stderr value

- Sources/Rugby/Common/Extensions/Crypto/Data+SHA1.swift
It's just a technical update. CryptoKit provides higher-level interfaces for performing cryptographic operations.
None
> 🤖 Use CryptoKit instead of CommonCrypto

- .github/scripts/spell_checker_whitelist.yml
- Docs/README.md
- Makefile
- Sources/Rugby/Commands/Doctor/Doctor.swift
- Sources/Rugby/main.swift
Added more suggestions and corrected older ones in `rugby doctor`.
None
> 🚑 Improved rugby doctor suggestions

- Package.swift
- Sources/Rugby/Core/Dependencies/Update/VersionParser.swift
- Tests/RugbyTests/Core/Dependencies/VersionParserTests.swift
Adding test support to the Rugby target, also testing VersionParser class
Helps with #236
> feat: Adding test support to Rugby target, testing VersionParser

- Makefile
- Sources/RugbyFoundation/Core/Plans/PlansParser.swift
- Tests/FoundationTests/Core/Common/Hashers/SHA1HasherTests.swift
- Tests/FoundationTests/Core/Plans/PlansParserTests.swift
- Tests/FoundationTests/Mocks/IFilesManagerMockMock.generated.swift
- Tests/FoundationTests/Mocks/IShellExecutorMock.generated.swift
- Tests/FoundationTests/Mocks/Mocks.swift
- Tests/Sourcery/AutoMockable.stencil
Add tests for `SHA1Hasher` and `PlansParser`.
fix #236 
> 👨🏻‍🔧 Add tests for `SHA1Hasher` and `PlansParser`

- README.md
- Sources/Rugby/Commands/Mixed/Plan.swift
- Sources/RugbyFoundation/Core/Plans/PlansParser.swift
- Tests/FoundationTests/Core/Plans/PlansParserTests.swift
I've added the hidden subcommand `plan list` for building autocomplete support.
Right now, [the Fig](https://github.com/withfig) supports 🏈 Rugby autocompletion. 
- https://github.com/withfig/autocomplete/pull/2105
- https://github.com/withfig/fig-swift-argument-parser
- https://swiftpackageindex.com/apple/swift-argument-parser/1.2.3/documentation/argumentparser/installingcompletionscripts
> ✈️ Plan list

- Sources/RugbyFoundation/XcodeProject/Models/BuildPhase.swift
- Tests/FoundationTests/Mocks/Manual/XcodeProject/Models/PBXBuildFile+Mock.swift
- Tests/FoundationTests/Mocks/Manual/XcodeProject/Models/PBXFileElement+Mock.swift
- Tests/FoundationTests/XcodeProject/Models/BuildPhaseTests.swift
I've fixed the issue with broken file references in build phases.
None
> 🐛 Fix broken file references

- Sources/RugbyFoundation/Core/Common/Hashers/FileContentHasher.swift
- Tests/FoundationTests/Core/Common/Hashers/FileContentHasherTests.swift
- Tests/FoundationTests/Mocks/FoundationHasherMock.generated.swift
- Tests/FoundationTests/Mocks/Mocks.swift
Sometimes modules can be outside of working directory (React Native).
Read more in the issue reference.
- #256 
- https://reactnative.dev/docs/environment-setup
> ⚛️ Add fallback to parent relative path in hashContext

- Sources/RugbyFoundation/Core/Build/BuildManager.swift
- Sources/RugbyFoundation/Vault/Commands/Build/Vault+Build.swift
- Tests/FoundationTests/Mocks/IInternalBuildManagerMock.generated.swift
It's a preparation step to #263 
- None
> ⚙️ Refactor BuildManager

- Docs/commands-help/build/full.md
- Docs/commands-help/build/pre.md
- Docs/commands-help/shortcuts/cache.md
- Docs/commands-help/use.md
- Docs/commands-help/warmup.md
- Sources/Rugby/Commands/Basic/Build/AdditionalBuildOptions.swift
- Sources/Rugby/Commands/Basic/Build/BuildOptions.swift
- Sources/RugbyFoundation/Core/Build/XcodeBuild/XcodeBuild.swift
- Tests/FoundationTests/Core/Build/BinariesStorageTests.swift
- Tests/FoundationTests/Core/Build/PrebuildManagerTests.swift
- Tests/FoundationTests/Core/Build/XcodeBuild/XcodeBuildTests.swift
> 🚀 Add build option `--result-bundle-path`

- Sources/RugbyFoundation/Core/Common/Hashers/BuildPhasesHasher.swift
- Sources/RugbyFoundation/Core/Common/Hashers/XcodeEnvResolver.swift
- Tests/FoundationTests/Core/Common/Hashers/XcodeEnvResolverTests.swift
I've added tests for `XcodeEnvResolver`.
- #236 
> ⚙️ Add tests for `XcodeEnvResolver`

- Sources/RugbyFoundation/Core/Common/Hashers/CocoaPodsScriptsHasher.swift
- Sources/RugbyFoundation/Core/Common/Hashers/TargetsHasher.swift
- Tests/FoundationTests/Core/Common/Hashers/CocoaPodsScriptsHasherTests.swift
I've added tests for `CocoaPodsScriptsHasher`.
- #236 
> ⚙️ Add tests for `CocoaPodsScriptsHasher`

- Sources/RugbyFoundation/Core/Common/Hashers/ConfigurationsHasher.swift
- Sources/RugbyFoundation/Core/Common/Hashers/TargetsHasher.swift
- Sources/RugbyFoundation/Vault/Vault.swift
- Tests/FoundationTests/Core/Common/Hashers/ConfigurationsHasherTests.swift
I've added tests for `ConfigurationsHasher`.
- #236 
> ⚙️ Add tests for `ConfigurationsHasher`

- Sources/RugbyFoundation/Core/Build/BuildManager.swift
- Sources/RugbyFoundation/Core/Common/XcodeProject/RugbyXcodeProject.swift
- Sources/RugbyFoundation/Core/Use/UseBinariesManager.swift
- Sources/RugbyFoundation/Core/Warmup/WarmupManager.swift
- Tests/FoundationTests/Core/Common/XcodeProject/RugbyXcodeProjectTests.swift
I've added tests for `RugbyXcodeProject`.
- #236 
> ⚙️ Add tests for `RugbyXcodeProject`

- Sources/RugbyFoundation/Core/Build/BuildManager.swift
- Sources/RugbyFoundation/Core/Build/BuildTargetsManager.swift
- Sources/RugbyFoundation/Core/Use/UseBinariesManager.swift
- Sources/RugbyFoundation/Core/Warmup/WarmupManager.swift
- Sources/RugbyFoundation/Vault/Commands/Vault+Use.swift
- Tests/FoundationTests/Core/Build/BuildTargetsManagerTests.swift
I've added tests for `BuildTargetsManager`.
- #236 
> ⚙️ Add tests for `BuildTargetsManager`

- Sources/RugbyFoundation/Core/Warmup/CacheDownloader.swift
- Sources/RugbyFoundation/Core/Warmup/Decompressor.swift
- Sources/RugbyFoundation/Core/Warmup/ReachabilityChecker.swift
- Sources/RugbyFoundation/Core/Warmup/URLSession.swift
- Sources/RugbyFoundation/Core/Warmup/WarmupManager.swift
- Sources/RugbyFoundation/Vault/Commands/Vault+Warmup.swift
- Tests/FoundationTests/Core/Warmup/CacheDownloaderTests.swift
- Tests/FoundationTests/Mocks/IDecompressorMock.generated.swift
- Tests/FoundationTests/Mocks/IReachabilityCheckerMock.generated.swift
- Tests/FoundationTests/Mocks/IURLSessionMock.generated.swift
- Tests/FoundationTests/Mocks/Mocks.swift
- codecov.yml
I've added tests for `CacheDownloader`.
- #236 
> ⚙️ Add tests for `CacheDownloader`

- Sources/RugbyFoundation/Core/Use/FileContentEditor.swift
- Sources/RugbyFoundation/Core/Use/UseBinariesManager.swift
- Tests/FoundationTests/Core/Use/FileContentEditorTests.swift
- Tests/FoundationTests/Core/Use/UseBinariesManagerTests.swift
- Tests/FoundationTests/Mocks/IFileContentEditorMock.generated.swift
- Tests/FoundationTests/Mocks/ILibrariesPatcherMock.generated.swift
- Tests/FoundationTests/Mocks/ISupportFilesPatcherMock.generated.swift
- Tests/FoundationTests/Mocks/Mocks.swift
I've added tests for `UseBinariesManagerTests`.
- #236 
> ⚙️ Add tests for `UseBinariesManagerTests`

- Sources/RugbyFoundation/Core/Warmup/ReachabilityChecker.swift
- Sources/RugbyFoundation/Core/Warmup/URLSession.swift
- Sources/RugbyFoundation/Vault/Commands/Vault+Warmup.swift
- Tests/FoundationTests/Core/Common/ProcessMonitor/ProcessInterruptionTaskTests.swift
- Tests/FoundationTests/Core/Common/SoundPlayerTests.swift
- Tests/FoundationTests/Core/Warmup/ReachabilityCheckerTests.swift
- Tests/FoundationTests/Mocks/IURLSessionMock.generated.swift
- codecov.yml
I've added tests for `RugbyFoundation/Core`.
- #236 
> ⚙️ Add tests for `RugbyFoundation/Core`

- Sources/RugbyFoundation/Core/Clear/Cleaner.swift
- Sources/RugbyFoundation/Vault/Commands/Vault+Clear.swift
- Tests/FoundationTests/Core/Clear/СleanerTests.swift
I've added tests for `СleanerTests`.
- #236 
> ⚙️ Add tests for `СleanerTests`

- Tests/FoundationTests/Core/Build/TargetTreePainter.swift
I've added tests for `TargetTreePainter`.
- #236 
> ⚙️ Add tests for `TargetTreePainter`

- Sources/RugbyFoundation/Core/Build/BuildManager.swift
- Sources/RugbyFoundation/Core/Build/XcodeBuild/XcodeBuild.swift
- Tests/FoundationTests/Core/Build/BuildManagerTests.swift
- Tests/FoundationTests/Core/Clear/СleanerTests.swift
- Tests/FoundationTests/Mocks/IBinariesCleanerMock.generated.swift
- Tests/FoundationTests/Mocks/IBuildTargetsManagerMock.generated.swift
- Tests/FoundationTests/Mocks/IEnvironmentCollectorMock.generated.swift
- Tests/FoundationTests/Mocks/IEnvironmentMock.generated.swift
- Tests/FoundationTests/Mocks/IProcessMonitorMock.generated.swift
- Tests/FoundationTests/Mocks/ITargetTreePainterMock.generated.swift
- Tests/FoundationTests/Mocks/IUseBinariesManagerMock.generated.swift
- Tests/FoundationTests/Mocks/IXcodeBuildMock.generated.swift
- Tests/FoundationTests/Mocks/Manual/Core/Build/XcodeBuild/XcodeBuildPaths+Mock.swift
- Tests/FoundationTests/Mocks/Mocks.swift
I've added tests for `BuildManager`.
- #236 
> ⚙️ Add tests for `BuildManager`

- Docs/commands-help/build/full.md
- Docs/commands-help/build/pre.md
- Sources/RugbyFoundation/Core/Build/BuildManager.swift
- Sources/RugbyFoundation/Core/Build/Prebuild/PrebuildManager.swift
- Sources/RugbyFoundation/Core/Use/UseBinariesManager.swift
- Sources/RugbyFoundation/Core/Warmup/WarmupManager.swift
- Sources/RugbyFoundation/Vault/Commands/Build/Vault+Build.swift
- Sources/RugbyFoundation/Vault/Commands/Build/Vault+Prebuild.swift
- Sources/RugbyFoundation/Vault/Commands/Vault+Use.swift
- Sources/RugbyFoundation/Vault/Commands/Vault+Warmup.swift
- Sources/RugbyFoundation/Vault/Vault.swift
- Tests/FoundationTests/Core/Build/BuildManagerTests.swift
- Tests/FoundationTests/Core/Build/PrebuildManagerTests.swift
- Tests/FoundationTests/Core/Use/UseBinariesManagerTests.swift
- Tests/FoundationTests/Core/Warmup/WarmupManagerTests.swift
- Renaming
- Fix docs routing
- None
> ⚙️ Refactoring

- Docs/commands-help/build/full.md
- Docs/commands-help/build/pre.md
- Docs/commands-help/delete.md
- Docs/commands-help/shortcuts/cache.md
- Docs/commands-help/use.md
- Docs/commands-help/warmup.md
- Sources/Rugby/Commands/Basic/Build/TargetsOptions.swift
I've reworded target options for clarity.
- Thanks @ivanglushko for spot the issue in #315 
> 📝 Reworded targets options

- Sources/RugbyFoundation/Core/Build/BuildTargetsManager.swift
- Sources/RugbyFoundation/XcodeProject/Models/Target/Target.swift
- Sources/RugbyFoundation/XcodeProject/Models/Target/TargetInterface.swift
- Tests/FoundationTests/Core/Build/BuildTargetsManagerTests.swift
- Tests/FoundationTests/Mocks/IInternalTargetMock.generated.swift
You can find more context in #324
- None
> 🐛 Fix caching applications

- Package.resolved
- Package.swift
- Sources/RugbyFoundation/Core/Warmup/Decompressor.swift
I've replaced Zip package with ZIPFoundation. More details in #320.
- https://github.com/weichsel/ZIPFoundation
- Closes #320 
> 🐦 Migrate to weichsel/ZIPFoundation

- Sources/RugbyFoundation/Core/Build/XcodeBuild/BuildLogFormatter.swift
- Sources/RugbyFoundation/Core/Build/XcodeBuild/XcodeBuild.swift
- Sources/RugbyFoundation/Core/Delete/DeleteTargetsManager.swift
- Sources/RugbyFoundation/Core/Test/TestplanEditor.swift
- Tests/FoundationTests/Core/Build/XcodeBuild/BuildLogFormatterTests.swift
- Tests/FoundationTests/Core/Build/XcodeBuild/XcodeBuildTests.swift
- Tests/FoundationTests/Core/Delete/DeleteTargetsManagerTests.swift
- Tests/FoundationTests/Core/Test/TestplanEditorTests.swift
- Tests/FoundationTests/Mocks/Mocks.swift
- Tests/FoundationTests/XcodeProject/Services/XcodeWorkspaceEditorTests.swift
It's the next step to implement the `_test run` command.
- None
> ⚙️ Add Testplan Editor

- Sources/RugbyFoundation/Core/Test/TestplanEditor.swift
- Tests/FoundationTests/Core/Test/TestplanEditorTests.swift
- Tests/FoundationTests/Mocks/ITestplanEditorMock.generated.swift
> ⚙️ Use value of parallelizable field from testplan targets

- Sources/RugbyFoundation/Core/Test/TestImpactManager.swift
- Sources/RugbyFoundation/XcodeProject/Models/Target/Target.swift
- Tests/FoundationTests/Mocks/IInternalTestImpactManagerMock.generated.swift
I've added sorting of affected test targets and ability to suspend some logs.
- None
> ⚙️ Test impact improvements

- .swiftlint.yml
- Sources/RugbyFoundation/Core/Common/Router.swift
- Sources/RugbyFoundation/Core/Test/TestManager.swift
- Sources/RugbyFoundation/Vault/Commands/Vault+Test.swift
- Sources/RugbyFoundation/XcodeProject/Models/Target/Target.swift
- Tests/FoundationTests/Core/Test/TestManagerTests.swift
- Tests/FoundationTests/Mocks/IInternalUseBinariesManagerMock.generated.swift
- Tests/FoundationTests/Mocks/Mocks.swift
I've added TestManager for the future test command.
- None
> ⚙️ Add test manager

- Sources/RugbyFoundation/Core/Test/TestManager.swift
- Sources/RugbyFoundation/Core/Test/TestplanEditor.swift
- Sources/RugbyFoundation/Vault/Commands/Vault+Test.swift
- Tests/FoundationTests/Core/Test/TestManagerTests.swift
- Tests/FoundationTests/Core/Test/TestplanEditorTests.swift
- Tests/FoundationTests/Mocks/ITestplanEditorMock.generated.swift
It's the next step to implement the `_test run` command.
- None
> Testplan expand path

- Package.resolved
- Package.swift
> 🤖 Bump dependencies

- Sources/RugbyFoundation/Core/Warmup/WarmupManager.swift
- Tests/FoundationTests/Core/Warmup/WarmupManagerTests.swift
- I've reworded some log messages about percents in the `warmup` command;
- I've added downloaded binaries percent to metics.
> ⚙️ Warmup percents

- Makefile
> 🚢 Add universal rugby release

- Sources/RugbyFoundation/Core/Build/BuildManager.swift
- Sources/RugbyFoundation/Core/Build/XcodeBuild/XcodeBuildExecutor.swift
- Sources/RugbyFoundation/Core/Delete/DeleteTargetsManager.swift
- Sources/RugbyFoundation/Core/Use/UseBinariesManager.swift
- Sources/RugbyFoundation/XcodeProject/Services/XcodeProjectDataSource.swift
- Tests/FoundationTests/Core/Build/BuildManagerTests.swift
- Tests/FoundationTests/Core/Build/XcodeBuild/XcodeBuildExecutorTests.swift
- Tests/FoundationTests/Core/Delete/DeleteTargetsManagerTests.swift
- Tests/FoundationTests/Core/Use/UseBinariesManagerTests.swift
I've added logs for post build stages.
- https://github.com/swiftyfinch/Rugby/discussions/357#discussioncomment-8769419
> 🎨 Post build logs

- Docs/remote-cache.md
Please, see the updated page: 🐳 [Remote Cache](https://github.com/swiftyfinch/Rugby/blob/81fa5df3cf6dd507fffbc3c6ed6da95337b7013b/Docs/remote-cache.md).
> 🐳 Improve remote cache documentation

- Sources/RugbyFoundation/Core/Build/XcodeBuild/XcodeBuildExecutor.swift
- Sources/RugbyFoundation/Utils/Public/Logger/LogsRotator.swift
- Sources/RugbyFoundation/Vault/Vault.swift
I've moved creating symbolic link to the latest log into LogsRotator.
- #368 
> ⚙️ Fix creating a symlink to the latest logs folder

- Package.resolved
- Package.swift
- https://github.com/swiftyfinch/Fish/pull/2
> 🤖 Bump Fish to 0.1.2

- .github/CODEOWNERS
- .github/dependabot.yml
> 🤖 Set default assignees and reviewers
