swiftyfinch/Rugby

Sources/rugby/Common/XcodeProj/Target/XcodeProj+AddTarget.swift
Sources/rugby/main.swift

Probably, sometimes first build target configuration leads to bugs.
We need to use the main build configuration from the Pods project.

🐛 Use Pods project main build configuration.

---

Docs/README.md
Sources/rugby/Commands/Cache/Command/CacheHeader.swift
Sources/rugby/Commands/Cache/Command/CacheRun.swift
Sources/rugby/Commands/Cache/Other/Errors/CacheError.swift
Sources/rugby/Commands/Doctor/Doctor.swift
Sources/rugby/Commands/Plan/Command/PlanRun.swift
Sources/rugby/Common/Command/Command.swift
Sources/rugby/Common/Environment/SDK.swift
Sources/rugby/Common/Environment/String+Env.swift
Sources/rugby/Common/History/EnvironmentCollector.swift
Sources/rugby/Common/History/HistoryWriter.swift
Sources/rugby/main.swift

Recently, there are lots of similar help requests. And I decided to add 🏈 Rugby doctor 😀
Feel free to suggest any additions to 🏈 Rugby doctor checklist.

🚑 Rugby doctor & runs history

---

README.md
Sources/Rugby/Commands/Cache/Command/CacheRun.swift
Sources/Rugby/Commands/Cache/Other/Checksums/ChecksumsProvider.swift
Sources/Rugby/Commands/Cache/Steps/CacheBuildStep.swift
Sources/Rugby/Commands/Cache/Steps/Prepare/CachePrepareStep.swift
Sources/Rugby/Commands/Cache/Steps/Prepare/Substeps/FindBuildPods.swift
Sources/rugby/Commands/Cache/Command/CacheRun.swift
Sources/rugby/Commands/Cache/Other/Checksums/ChecksumsProvider.swift
Sources/rugby/Commands/Cache/Steps/CacheBuildStep.swift
Sources/rugby/Commands/Cache/Steps/Prepare/CachePrepareStep.swift
Sources/rugby/Commands/Cache/Steps/Prepare/Substeps/FindBuildPods.swift

Before this pull request, all pod checksums were calculated at the start of 🏈 Rugby run.
But that's not enough because some pods have scripts that can generate files.
It could make checksums stale right after build.
That request add recalculation build pods checksums after the build process.

🐛 Recalculate checksums after build

---

Package.resolved
Package.swift
Sources/Rugby/Commands/Cache/Other/Build/LogFormatter.swift
Sources/Rugby/Commands/Cache/Other/Build/XcodeBuild.swift
Sources/Rugby/Commands/Cache/Other/Build/XcodeBuildRunner.swift
Sources/Rugby/Commands/Cache/Other/Errors/CacheError.swift
Sources/Rugby/Commands/Cache/Steps/CacheCleanupStep.swift
Sources/Rugby/Commands/Cache/Steps/Prepare/CachePrepareStep.swift
Sources/Rugby/Commands/Clean/Clean.swift
Sources/Rugby/Common/Environment/String+Env.swift
Sources/Rugby/Common/History/HistoryWriter.swift
Sources/Rugby/Common/Utils/ShellRunner.swift
Sources/Rugby/main.swift

I used https://github.com/thii/xcbeautify/pull/55 to beautify build logs.
After that pull request, we can use `cat .rugby/.build.log` to see the already formatted output.
Also, I decided to make `rugby clean` command visible again)

🎨 Beautify build logs

---

Docs/Plans.md
Sources/Rugby/Commands/Cache/Command/CacheHeader.swift
Sources/Rugby/Commands/Plan/Parser/DecodableModels/CacheDecodable.swift
Sources/Rugby/Commands/Plan/Subcommands/PlansExample.swift

Sometimes after the bump patch version, it breaks the build of dependent pods.
Option `--graph` fix these cases. Now I decided to enable it by default because these cases are hard to investigate.
Also, in that case, you need to use full rebuild with `--ignore-checksums` option.
If you encourage that `rugby` process takes more time you can disable this option by passing `--no-graph`.

🚧 Use `--graph` by default

---

Docs/Cache.md
Docs/Plans.md
Sources/Rugby/Commands/Cache/Command/CacheHeader.swift
Sources/Rugby/Commands/Plan/Subcommands/PlansExample.swift

In this request, I opened include and focus options of Cache command.
These options were added a month ago and finally, look stable enough.
You can include some local pods to cache:
```bash
rugby --include MyLocalPods1 MyLocalPods2
```
If you want to focus on some local pods and cache all others:
```bash
rugby --focus MyFocusedPod1 MyFocusedPod2
```
If you want to cache all local pods ([Maybe someday there will be another solution](https://github.com/apple/swift-argument-parser/pull/317)):
```bash
rugby --focus ""
```

👀 Open local pods options

---

.github/workflows/regress.yml
Sources/Rugby/Common/Utils/ProcessMonitor.swift
Sources/Rugby/Common/Utils/ShellRunner.swift
Sources/Rugby/main.swift
TestProject/Fastlane/Xcode

closes #67
1. Sometimes shell commands still print the interruption log. I couldn't see the ability to mute it with `SwiftShell`:
```
Shell 🐚 bundle exec pod install || bundle exec pod install --repo-update
^C%                                                                             Traceback (most recent call last):
20: from /Users/swiftyfinch/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
19: from /Users/swiftyfinch/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
18: from /Users/swiftyfinch/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.22/exe/bundle:37:in `<top (required)>'
17: from /Users/swiftyfinch/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.22/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
16: from …
```

🐛 Stop all subcommands by pressing ^C

---

Sources/Rugby/Common/XcodeProj/Scheme/XcodeProj+RemoveSchemes.swift

Hello. Rugby is very nice tool!
I've found the issue so sent this pull request.
Rugby cache command occurred error if fish shell is default.
I get the following error.
```fish
[2s] Prepare ✓
[1s] Build ✓
[1s] Integration ✓
Clean up Remove schemes
⛔️ Error: fish: Variables cannot be bracketed. In fish, please use {$USER}.
echo ${USER} 
^
🚑 Call doctor for more help: rugby doctor
```
This issue seems to be due to the assumption that the shell command is bash or zsh.
Therefore, by pinning the execution shell to bash is resolve this issue.

Fix an error if the default shell is fish.

---

Docs/Plans.md
Sources/Rugby/Commands/Plan/Command/PlanRun.swift
Sources/Rugby/Commands/Plan/Parser/DecodableModels/PlansDecodable.swift
Sources/Rugby/Commands/Plan/Parser/DecodableModels/ShellDecodable.swift
Sources/Rugby/Commands/Plan/Parser/Errors/PlanError.swift
Sources/Rugby/Commands/Plan/Parser/PlanParser.swift
Sources/Rugby/Commands/Plan/Subcommands/PlansExample.swift
Sources/Rugby/Commands/Plan/Subcommands/PlansReference.swift

Added the ability to use `Plans` command in `.rugby/plans.yml` fie.
```yml
- dev:
- command: plans
run: base # And use base plan here
- command: cache
- base: # Preapre base plan
- command: shell
run: xcodegen
verbose: false
- command: shell
run: pods -q
```
Beware of recursion 😱
See the issue for more info:
Closes #68

🚀 Added ability to use Plans command recursively

---

Sources/Rugby/Commands/Plan/Subcommands/PlansShell.swift
Sources/Rugby/Common/XcodeProj/Project/ProjectProvider.swift

Shell commands can modify Xcode projects.
Need to reset cache after each one for stable execution.
Closes #90
❤️ Thanks for contributing to the Rugby!

🐛 Reset projects cache after shell command

---

Sources/Rugby/Commands/Cache/Other/Build/XcodeBuild.swift

Need to escape SYMROOT variable because some paths can contain spaces.
Closes https://github.com/swiftyfinch/Rugby/issues/87#issuecomment-982652567
❤️ Thanks for contributing to the Rugby!

🐛 Escape SYMROOT variable

---

Sources/Rugby/Commands/Cache/Other/Lockfile/Lockfile.swift

Made parsing `EXTERNAL SOURCES` in `Podfile.lock` more flexible.
Probably, there can be non `String` values.
Close #113

🐛 Make parsing external source more flexible

---

Sources/Rugby/Commands/Cache/Other/Build/XcodeBuild.swift

1. Use native Swift `pwd` method instead of `$(PWD)`;
2. Remove `set -o pipefail`. Need to regress it before releasing a new version.
Close #117

🐛 Support `fish` shell

---

Sources/Rugby/Commands/Cache/Command/CacheHeader.swift
Sources/Rugby/Commands/Cache/Command/CacheRun.swift
Sources/Rugby/Commands/Cache/Other/Build/XcodeBuild.swift
Sources/Rugby/Commands/Cache/Other/Checksums/CacheManager.swift
Sources/Rugby/Commands/Cache/Other/Errors/CacheError.swift
Sources/Rugby/Commands/Cache/Other/PatchConfigs/CacheIntegration.swift
Sources/Rugby/Commands/Cache/Steps/CacheBuildStep.swift
Sources/Rugby/Commands/Cache/Steps/Prepare/CachePrepareStep.swift
Sources/Rugby/Commands/Cache/Steps/Prepare/Substeps/FindBuildPods.swift
Sources/Rugby/Commands/Plan/Parser/DecodableModels/CacheDecodable.swift
Sources/Rugby/Common/Environment/String+Env.swift
TestProject/TestProject/TestProject.xcodeproj/project.pbxproj

Added arch to products directory.
Now we can build with the same arch for different sdks. For example:
```shell
rugby -s sim sim ios -a x86_64 arm64 arm64
```
```
Debug-iphoneos-arm64
Debug-iphonesimulator-arm64
Debug-iphonesimulator-x86_64
```
But I think we still need the better api.
#93 #123

🔭 `[Beta]` Add arch to product directory

---

Sources/Rugby/Commands/Cache/Other/Errors/CacheError.swift
Sources/Rugby/Commands/Cache/Steps/CacheCleanupStep.swift
Sources/Rugby/Commands/Cache/Steps/Prepare/CachePrepareStep.swift
Sources/Rugby/Commands/Cache/Steps/Prepare/Substeps/BuildTargets.swift
Sources/Rugby/Common/Environment/String+Env.swift
Sources/Rugby/Common/XcodeProj/Project/PBXProject+BuildSettings.swift

Before using the **cache** command we need to know if the project already has been patched.
The legacy solution was:
```swift
guard selectedPodsChain.count >= input.selectedPods.count else { throw CacheError.cantFindPodsTargets }
```
But there are some cases when it just doesn't work.
I think the better way is to add a concrete variable to the **Pods** project. Then check if that variable already exists and show an error with a suggestion to call `pod install`.
None

🐛 Use another way to identify if a project already use 🏈 Rugby

---

Sources/Rugby/Commands/Cache/Steps/CacheIntegrateStep.swift
Sources/Rugby/Common/Environment/String+Env.swift

Use absolute paths without Xcode variables.
I didn't add new tests for this fix, but the issue can be reproduced with these changes in `Podfile`:
```diff
-  use_frameworks!
+ pod 'hippy', '2.11.6'
```
Closes #125

🐛 Use absolute paths without Xcode variables

---

Sources/Rugby/Commands/Cache/Other/PatchConfigs/CacheIntegration.swift
Sources/Rugby/Commands/Cache/Steps/Prepare/CachePrepareStep.swift

We certainly need a safer way to patch product paths, but it's hard to do without losing performance.
So, for now, I've added one more workaround.
Closes #134 

🐛 Patch targets with products

---

Sources/Rugby/Commands/Cache/Steps/Prepare/CachePrepareStep.swift
Sources/Rugby/Commands/Cache/Steps/Prepare/Substeps/SelectPods.swift

Sometimes XCFrameworks weren't excluded correctly.
It was so, when some of XCFrameworks were dependencies of build targets.
In this request all XCFrameworks should be excluded from build targets after finding all of them.
None

🐛 Exclude xcframeworks after finding all build targets

---

Sources/Rugby/Commands/Cache/Steps/CacheCleanupStep.swift

Sometimes during clean step Rugby removes necessary dependencies.
That because CocoaPods use implicit dependencies, and if we remove one of them some transitive dependencies can be removed alltogether. So we need to make all dependencies explicit.
None

🐛 Exclude remaining targets explicitly

---

Docs/Cache.md
Docs/Plans.md
Sources/Rugby/Commands/Cache/Command/CacheHeader.swift
Sources/Rugby/Commands/Cache/Other/Build/XCARGSProvider.swift
Sources/Rugby/Commands/Cache/Steps/CacheBuildStep.swift
Sources/Rugby/Commands/Cache/Steps/Prepare/Substeps/FindBuildPods.swift
Sources/Rugby/Commands/Plan/Command/PlanHeader.swift
Sources/Rugby/Commands/Plan/Parser/DecodableModels/CacheDecodable.swift
Sources/Rugby/Commands/Plan/Subcommands/PlansExample.swift

I added a new experimental flag `--off-debug-symbols`.
With this flag, 🏈 Rugby will off debug symbols generation and strip all already generated symbols.
It can be valuable in enormous projects.
Usually, we don't need to debug binaries. It will be better to focus on a group of pods developing currently.
In some cases, it speeds up debugger attachment by 16x (147s vs 9s) in my work project.
Also, it slightly speeds up app launch time.
I've collected some metrics in my work project:
```bash
Metric             | Speed up
-------------------------------------
Build Time         | 6%
Breakpoint Await   | x16
Launch Time        | 23%
build/ folder size | 21%
```
None

🚀 Add ability to off debug symbols

---

.github/scripts/spell_checker_whitelist.yml
Docs/README.md
Sources/Rugby/Commands/Cache/Command/CacheHeader.swift
Sources/Rugby/Commands/Cache/Other/Backup/BackupManager.swift
Sources/Rugby/Commands/Cache/Steps/Prepare/CachePrepareStep.swift
Sources/Rugby/Commands/Clean/Clean.swift
Sources/Rugby/Commands/Drop/Steps/DropRemoveStep.swift
Sources/Rugby/Commands/Rollback/Rollback.swift
Sources/Rugby/Common/Environment/String+Env.swift
Sources/Rugby/Common/History/HistoryWriter.swift
Sources/Rugby/Common/Utils/BackupManager.swift
Sources/Rugby/Common/Utils/FileManager.swift
Sources/Rugby/Common/XcodeProj/Scheme/XcodeProj+RemoveSchemes.swift
Sources/Rugby/main.swift
TestProject/Fastlane/Fastfile
TestProject/Fastlane/Tests/Commands/Cache
TestProject/Fastlane/Tests/Commands/Drop
TestProject/Fastlane/Tests/Commands/Focus
TestProject/Fastlane/Tests/Commands/Plans
TestProject/Fastlane/Utils

After this pull request we can discard all 🏈 Rugby changes instantly without calling `pod install`.
Closes #174

🔭 Rollback

---

Sources/Rugby/Commands/Cache/Other/Checksums/CombinedChecksum.swift
Sources/Rugby/Common/Extensions/String+File.swift

Current directory detection is looking for `.` (File extension?). This is problematic for directories that contain a `.`, or relative paths `../`. This change uses URL apis check if a file is a directory.
On a semi-large react-native project (lots of relative `../node_modules` imports, this speeds up the run of rugby dramatically), it was incorrectly checksumming the parent directory, which in many cases was the huge `node_modules` directory. I'm not entirely sure why, but it was also causing the pods to get checksummed twice (once in prepare and again in build phase).
Before:
```
[3m] Prepare ✓
[3m 36s] Build ✓
[1s] Integration ✓
[1s] Clean up ✓
[6m 37s] Cached 139/166 pods.
[!] Project size ↓83%
[!] Indexing files count ↓96%
[!] Targets count ↓83%
[6m 37s] Let's roll 🏈
66.36s user …
```

🔭 Improve directory detection: Big performance improvement for certain setups

---

Sources/Rugby/Commands/Cache/Command/CacheRun.swift
Sources/Rugby/Commands/Cache/Steps/CacheBuildStep.swift
Sources/Rugby/Commands/Cache/Steps/CacheCleanupStep.swift
Sources/Rugby/Commands/Cache/Steps/CacheIntegrateStep.swift
Sources/Rugby/Commands/Cache/Steps/Prepare/CachePrepareStep.swift
Sources/Rugby/Commands/Clean/Clean.swift
Sources/Rugby/Commands/Drop/Command/DropRun.swift
Sources/Rugby/Commands/Drop/Steps/DropPrepareStep.swift
Sources/Rugby/Commands/Drop/Steps/DropRemoveStep.swift
Sources/Rugby/Commands/Focus/Command/FocusRun.swift
Sources/Rugby/Commands/Focus/Steps/FocusPrepareStep.swift
Sources/Rugby/Commands/Plan/Command/PlanRun.swift
Sources/Rugby/Commands/Plan/Parser/DecodableModels/CacheDecodable.swift
Sources/Rugby/Commands/Plan/Parser/DecodableModels/DropDecodable.swift
Sources/Rugby/Commands/Plan/Parser/DecodableModels/FocusDecodable.swift
Sources/Rugby/Commands/Plan/Parser/DecodableModels/ShellDecodable.swift
Sources/Rugby/Commands/Plan/Subcommands/PlansReference.swift
Sources/Rugby/Commands/Plan/Subcommands/PlansShell.swift
Sources/Rugby/Commands/Rollback/Rollback.swift
Sources/Rugby/Common/Command/Command.swift
Sources/Rugby/Common/Command/CommonFlags.swift
Sources/Rugby/Common/Command/ParsableCommand+Metrics.swift
Sources/Rugby/Common/Command/ParsableCommand+Output.swift
Sources/Rugby/Common/LogPrinter/Printers/RugbyPrinter.swift

CI or otherwise logged terminal sessions end up with a huge amount of output with stuff like `Build Building sim-x86_64` which various number of dots. For non-interactive sessions this loading spinner isn't as useful and bloats the output.
N/A

Add --non-interactive flag which limits spinner output for non-interactive terminals (Ex: CI)

---

Sources/Rugby/Commands/Cache/Steps/Prepare/CachePrepareStep.swift

Sometimes the default CLT path can contain whitespace characters.
I've made checking more flexible.
None

🐛 Fixed checking that Xcode CLT set

---

Sources/Rugby/Commands/Cache/Steps/CacheBuildStep.swift

It's a tiny improvement which shows `config name` during building.
For example, `config: Staging With Spaces`.
It can be useful when the project don't have `Debug` config as default one. Users can see error during building process and interrupt it.
None

🎨 Print config name during building

---

.github/workflows/regress.yml

> The macOS-10.15 environment is deprecated, consider switching to macos-11(macos-latest), macos-12 instead.
For more details see https://github.com/actions/virtual-environments/issues/5583
Unfortunately, I have to remove support Xcode 12.
If you can't update your mac OS and Xcode to newer version you can use `brew` for downloading 🏈 Rugby as a binary.
More information here: https://github.com/swiftyfinch/Rugby/discussions/71
None

🤖 Remove Xcode 12 build job

---

README.md

The video in the README was just showing as the broken file icon on Firefox and Chrome.

🐛 Fixed video in README

---

Sources/Rugby/Commands/Cache/Other/Checksums/CombinedChecksum.swift

Fix Crash with useContentChecksums.
May crash when `cache` with useContentChecksums if there's any symlink file.
Shouldn't include these symlink when calculate checksums.

🐛 Fix Crash with useContentChecksums

---

Sources/RugbyFoundation/Core/Build/BuildError.swift
Sources/RugbyFoundation/Core/Build/BuildManager.swift
Sources/RugbyFoundation/Core/Build/XcodeBuild/BuildLogFormatter.swift
Sources/RugbyFoundation/Core/Build/XcodeBuild/XcodeBuildExecutor.swift
Sources/RugbyFoundation/Core/Common/ShellExecuter.swift
Sources/RugbyFoundation/Utils/Internal/Extensions/Swift/String/String+PrefixCount.swift
Sources/RugbyFoundation/Utils/Internal/Extensions/Swift/String/String+Removing.swift
Sources/RugbyFoundation/Utils/Internal/Extensions/Swift/String/String+UppercasedFirstLetter.swift
Sources/RugbyFoundation/Vault/Commands/Vault+Build.swift
Tests/FoundationTests/Core/Build/XcodeBuild/BuildLogFormatterTests.swift
Tests/FoundationTests/Core/Build/XcodeBuild/XcodeBuildExecutorTests.swift
Tests/FoundationTests/Core/Plans/PlansParserTests.swift
Tests/FoundationTests/Mocks/IBuildLogFormatterMock.generated.swift
Tests/FoundationTests/Mocks/IFileMock.generated.swift
Tests/FoundationTests/Mocks/IFilesManagerMock.generated.swift
Tests/FoundationTests/Mocks/IFolderMock.generated.swift
Tests/FoundationTests/Mocks/IShellExecutorMock.generated.swift
Tests/FoundationTests/Mocks/Mocks.swift
Tests/FoundationTests/Mocks/ReadableStreamMock.generated.swift
Tests/FoundationTests/Utils/Internal/Extensions/Swift/InternalStringTests.swift

I've reworked build error formatting, fixed some issues and added tests.
- https://github.com/tuist/xcbeautify

👨🏻‍🎨 Rework build errors formatting

---

Sources/RugbyFoundation/Core/Use/FileContentEditor.swift
Sources/RugbyFoundation/Core/Use/SupportFilesPatcher.swift
Sources/RugbyFoundation/Utils/Internal/Extensions/Foundation/String+RegEx.swift
Sources/RugbyFoundation/Utils/Internal/Extensions/Swift/String/String+Quotes.swift
Tests/FoundationTests/Core/Use/FileContentEditorTests.swift
Tests/FoundationTests/Core/Use/SupportFilesPatcherTests.swift

I updated the code to use '\b' for match endings, removing the initial boundary (as '\b' at the beginning didn't work). Tested successfully in my project and added relevant unit tests. Further testing may be required.
https://github.com/swiftyfinch/Rugby/issues/271

🐛 Fix path replacement issue

---

Docs/commands-help/env.md
Sources/Rugby/Commands/Utils/Env.swift
Sources/Rugby/Core/Dependencies/Environment/Environment.swift
Sources/Rugby/Core/RunnableCommand/RunnableCommand.swift
Sources/Rugby/Rugby.swift
Sources/RugbyFoundation/Core/Build/BuildManager.swift
Sources/RugbyFoundation/Core/Common/IEnvironment.swift
Sources/RugbyFoundation/Vault/Commands/Build/Vault+Build.swift
Sources/RugbyFoundation/Vault/Vault.swift

- I've renamed the feature toggles service to the environment;
- And I've added the new environment variable to set shared folder root path.\
Read more in updated docs.
- None

🚀 Add ability to set shared folder root path

---

.github/workflows/checks.yml
Tests/.swiftlint.yml
Tests/FoundationTests/Core/Build/LibrariesPatcherTests.swift
Tests/FoundationTests/Core/Build/PrebuildManagerTests.swift
Tests/FoundationTests/Core/Build/XcodeBuild/BuildLogFormatterTests.swift
Tests/FoundationTests/Core/Build/XcodeBuild/XcodeBuildExecutorTests.swift

I've added a separate `.swiftlint` file to **Tests** folder to use more lenient rules in tests. 
- https://github.com/realm/SwiftLint#using-multiple-configuration-files

⚙️ Add separate `.swiftlint` file to tests

---

Docs/commands-help/build/full.md
Docs/commands-help/build/pre.md
Docs/commands-help/shortcuts/cache.md
Docs/commands-help/use.md
Docs/commands-help/warmup.md
Sources/Rugby/Commands/Basic/Build/AdditionalBuildOptions.swift
Sources/Rugby/Commands/Basic/Build/Build.swift
Sources/Rugby/Commands/Basic/Build/BuildOptions.swift
Sources/Rugby/Commands/Mixed/Shortcuts.swift
Tests/.swiftlint.yml

I've kept `--result-bundle-path` only in full build and cache commands.
This option is passed to `xcodebuild` which is used only in these commands.
- None

⚙️ Keep `--result-bundle-path` only in `full build` and `cache` commands

---

Package.resolved
Package.swift
Sources/RugbyFoundation/Core/Common/Hashers/FileContentHasher.swift
Tests/FoundationTests/Core/Common/Hashers/FileContentHasherTests.swift

Sometimes modules can be outside of working directory.
We need to find nearest common parent to convert paths to relative ones during hash process.
Read more in the issue reference.
- #258 
- #279 

🐛 Fixed relative paths in file hasher when they even outside of `$PWD` parent

---

Sources/RugbyFoundation/Core/Common/Hashers/BuildPhasesHasher.swift
Sources/RugbyFoundation/Core/Common/Hashers/BuildRulesHasher.swift
Sources/RugbyFoundation/Core/Common/Hashers/CocoaPodsScriptsHasher.swift
Sources/RugbyFoundation/Core/Common/Hashers/FileContentHasher.swift
Sources/RugbyFoundation/Core/Common/Hashers/TargetsHasher.swift
Sources/RugbyFoundation/Vault/Vault.swift
Tests/FoundationTests/Core/Common/Hashers/BuildPhaseHasherTests.swift
Tests/FoundationTests/Mocks/IFileContentHasherMock.generated.swift
Tests/FoundationTests/Mocks/IXcodeEnvResolverMock.generated.swift
Tests/FoundationTests/Mocks/Mocks.swift

I've added tests for `BuildPhaseHasher`.
- None

⚙️ Add tests for `BuildPhaseHasher`

---

Sources/Rugby/Utils/Regex/Regex.swift
Tests/RugbyTests/Utils/Regex/RegexTests.swift

I've fixed an issue when a target name has a plus sign.
For example, `Keyboard+LayoutGuide-framework`.
```sh
> rugby cache -t Keyboard+LayoutGuide-framework
```
- None

🐛 Fix bug when target name has plus sign

---

Sources/RugbyFoundation/Core/Common/Hashers/ProductHasher.swift
Sources/RugbyFoundation/Core/Common/Hashers/TargetsHasher.swift
Sources/RugbyFoundation/Vault/Vault.swift
Tests/FoundationTests/Core/Common/Hashers/ProductHasherTests.swift
Tests/RugbyTests/Utils/Regex/RegexTests.swift

I've added tests for `ProductHasher`.
- #236 

⚙️ Add tests for `ProductHasher`

---

Sources/RugbyFoundation/Core/Build/BuildManager.swift
Sources/RugbyFoundation/Core/Common/Hashers/BuildRulesHasher.swift
Sources/RugbyFoundation/Core/Common/Hashers/TargetsHasher.swift
Sources/RugbyFoundation/Core/Use/UseBinariesManager.swift
Sources/RugbyFoundation/Core/Warmup/WarmupManager.swift
Sources/RugbyFoundation/Vault/Vault.swift
Tests/FoundationTests/Core/Common/Hashers/TargetsHasherTests.swift
Tests/FoundationTests/Mocks/IBuildPhaseHasherMock.generated.swift
Tests/FoundationTests/Mocks/IBuildRulesHasherMock.generated.swift
Tests/FoundationTests/Mocks/ICocoaPodsScriptsHasherMock.generated.swift
Tests/FoundationTests/Mocks/IConfigurationsHasherMock.generated.swift
Tests/FoundationTests/Mocks/IProductHasherMock.generated.swift
Tests/FoundationTests/Mocks/IXcodeEnvResolverMock.generated.swift
Tests/FoundationTests/Mocks/Manual/XcodeProject/Models/BuildRule+Mock.swift
Tests/FoundationTests/Mocks/Mocks.swift

I've added tests for `TargetsHasher`.
- #236 

⚙️ Add tests for `TargetsHasher`

---

Sources/Rugby/Commands/Basic/Rollback.swift
Sources/RugbyFoundation/Core/Rollback/BackupManager.swift
Tests/FoundationTests/Core/Rollback/BackupManagerTests.swift
Tests/FoundationTests/Mocks/IXcodeProjectMock.generated.swift
Tests/FoundationTests/Mocks/Mocks.swift

I've added tests for `BackupManager`.
- #236 

⚙️ Add tests for `BackupManager`

---

Sources/RugbyFoundation/XcodeProject/Services/XcodeTargetsEditor.swift

We discovered a crash in rugby when the application has a very large number of targets that need to be deleted. The crash occurs due to asynchronous removal of targets. In the merge request I made this deletion synchronous
```
Thread 10 Crashed:
0   libsystem_kernel.dylib        	    0x7ff815a891e2 __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff815ac0ee6 pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff8159e7b45 abort + 123
3   libsystem_malloc.dylib        	    0x7ff8158fe752 malloc_vreport + 888
4   libsystem_malloc.dylib        	    0x7ff815913a08 malloc_zone_error + 183
5   libswiftCore.dylib            	    0x7ff8253b9290 _swift_release_dealloc + 16
6   libswiftCore.dylib            	    0x7ff8253b9dab bool …
```

🐛 Fixed concurrent crash on target delete

---

.github/workflows/checks.yml
.github/workflows/release.yml
Example/Example/Example.xcodeproj/project.pbxproj
Example/Example/ExampleTests/ExampleTests.swift
Example/Podfile
Example/Podfile.lock

I've fixed some GitHub action issues:
- Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3.
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
- Run `swiftformat . --lint --quiet --reporter github-actions-log`
error: Unknown rule 'preferForLoop'. Did you mean 'preferKeyPath'?
- [Smoke (Libraries): Example/Pods/AutoMate/AutoMate/XCTest extensions/XCTestCase.swift#L51](https://github.com/swiftyfinch/Rugby/pull/327/files#annotation_18091860500)
'recordFailure(withDescription:inFile:atLine:expected:)' is deprecated: Replaced by 'record(_:)'
- None

⚙️ Fix GitHub actions

---

Sources/RugbyFoundation/Core/Build/BuildError.swift
Sources/RugbyFoundation/Core/Build/BuildManager.swift
Sources/RugbyFoundation/Core/Build/XcodeBuild/XcodeBuild.swift
Sources/RugbyFoundation/Core/Build/XcodeBuild/XcodeBuildExecutor.swift
Sources/RugbyFoundation/Vault/Commands/Build/Vault+Build.swift
Sources/RugbyFoundation/Vault/Commands/Build/Vault+Prebuild.swift
Sources/RugbyFoundation/Vault/Vault.swift
Tests/FoundationTests/Core/Build/XcodeBuild/XcodeBuildExecutorTests.swift
Tests/FoundationTests/Core/Build/XcodeBuild/XcodeBuildTests.swift
Tests/FoundationTests/Core/Clear/CleanerTests.swift
Tests/FoundationTests/Mocks/IXcodeBuildMock.generated.swift

⚙️ Refactoring XcodeBuild

---

Sources/RugbyFoundation/Core/Build/BuildManager.swift
Sources/RugbyFoundation/Core/Build/BuildTargetsManager.swift
Sources/RugbyFoundation/Core/Build/Prebuild/PrebuildManager.swift
Sources/RugbyFoundation/Core/Common/TargetsScope.swift
Sources/RugbyFoundation/Core/Use/UseBinariesManager.swift
Sources/RugbyFoundation/Vault/Commands/Build/Vault+Build.swift
Sources/RugbyFoundation/Vault/Commands/Build/Vault+Prebuild.swift
Sources/RugbyFoundation/Vault/Commands/Vault+Use.swift
Tests/FoundationTests/Core/Build/BuildManagerTests.swift
Tests/FoundationTests/Core/Build/PrebuildManagerTests.swift
Tests/FoundationTests/Mocks/IBuildTargetsManagerMock.generated.swift
Tests/FoundationTests/Mocks/IInternalBuildManagerMock.generated.swift

⚙️ Refactoring the way to select targets

---

Sources/RugbyFoundation/XcodeProject/Extensions/XcodeProj/PBXProj/PBXProj+Dependencies.swift

Sometimes a project path is relative to the project.
For example, `'../../Pods/SnapKit.xcodeproj'` should be `'SnapKit.xcodeproj'`.
It breaks adding a transitive dependency from an another subproject explicitly.
- None

🐛 Fix adding transitive dependency in multi-project configuration

---

Docs/commands-help/test/pass.md
Sources/Rugby/Commands/Basic/Test.swift
Sources/Rugby/Core/Routing.swift
Sources/Rugby/Core/RunnableCommand/RunnableCommand.swift
Sources/RugbyFoundation/Core/Common/Git.swift
Sources/RugbyFoundation/Core/Env/EnvironmentCollector.swift
Sources/RugbyFoundation/Core/Test/TestImpactManager.swift
Sources/RugbyFoundation/Vault/Commands/Vault+Test.swift
Sources/RugbyFoundation/Vault/Vault.swift
Tests/FoundationTests/Core/Common/GitTests.swift
Tests/FoundationTests/Core/Env/EnvironmentCollectorTests.swift
Tests/FoundationTests/Core/Test/TestImpactManagerTests.swift
Tests/FoundationTests/Mocks/IGitMock.generated.swift
Tests/FoundationTests/Mocks/Mocks.swift

I've added ability to mark test passed only if there are no git changes and the current branch is not behind to target one.
```shell
> rugby _test pass --up-to-date-branch main
> rugby _test pass -u main
```
The main idea is to use it in `rugby/plans.yml`:
```yml
basic:
- command: shell
argument: pod install
- command: _test pass
up-to-date-branch: main
- command: cache
```
It will mark all test targets as passed after creating a new fresh git branch.
And will skip it if you are already in the middle of your working process and use the `rugby basic` plan again.
- None

🚀 Add option `--up-to-date-branch` to `test pass` command

---

Sources/RugbyFoundation/XcodeProject/Extensions/XcodeProj/PBXProj/PBXProj+Dependencies.swift

This request fixes missing bundle product folders after the build process in the multi-project configuration.
- #338 

🐛 Copy reference to subproject before fixing relative path

---

Sources/RugbyFoundation/Core/Rollback/BackupManager.swift
Tests/FoundationTests/Core/Rollback/BackupManagerTests.swift

In some cases it is necessary to rewrite a whole folder during restoring a backup.
For example, when an original Pods folder contains a temporary Rugby scheme.
- None

🐛 Rewrite backup folders instead of copying files

---

.swiftlint.yml
Sources/RugbyFoundation/Core/Test/TestManager.swift
Sources/RugbyFoundation/Vault/Commands/Vault+Test.swift
Tests/FoundationTests/Core/Test/TestManagerTests.swift

It's the next step to implement the `_test run` command.
- None

⚙️ Add ability to mark test targets as passed if all tests are succeed

---

.github/workflows/checks.yml
Docs/commands-help/build/full.md
Docs/commands-help/shortcuts/cache.md
Docs/commands-help/test/impact.md
Docs/commands-help/test/pass.md
Docs/commands-help/test/run.md
Docs/commands-help/use.md
Docs/commands-help/warmup.md
Example/Tests/cache_tests.sh
Example/Tests/cache_tests_multiproj.sh
Sources/Rugby/Commands/Basic/Build/AdditionalBuildOptions.swift
Sources/Rugby/Commands/Basic/Build/BuildOptions.swift
Sources/Rugby/Commands/Basic/Use.swift

I've added an ability to disallow code signing.
It can speed up `xcodebuild` process, especially in huge projects.
```sh
> rugby cache --skip-signing
```
I've tested on [devMEremenko/XcodeBenchmark](https://github.com/devMEremenko/XcodeBenchmark) and got ~10% speedup (107/121s).
- None

Add flag `--skip-signing`

---

.github/workflows/checks.yml
.github/workflows/release.yml
Package.swift

🤖 Bump minimum macOS and Swift version

---

Sources/RugbyFoundation/Core/Rollback/BackupManager.swift
Sources/RugbyFoundation/Core/Test/TestManager.swift
Tests/FoundationTests/Core/Rollback/BackupManagerTests.swift
Tests/FoundationTests/Core/Test/TestManagerTests.swift

I've reverted `backup` command changes, because there was an issue with restoring custom (non-Pods) projects.
And I've added removing the `RugbyPods` scheme outside of restoring process.
This solution looks like more stable one.

🐛 Revert backup changes

---

Docs/commands-help/warmup.md
Sources/Rugby/Commands/Basic/Warmup.swift
Sources/RugbyFoundation/Core/Warmup/CacheDownloader.swift
Sources/RugbyFoundation/Core/Warmup/ReachabilityChecker.swift
Sources/RugbyFoundation/Core/Warmup/WarmupManager.swift
Tests/FoundationTests/Core/Warmup/CacheDownloaderTests.swift
Tests/FoundationTests/Core/Warmup/ReachabilityCheckerTests.swift
Tests/FoundationTests/Core/Warmup/WarmupManagerTests.swift
Tests/FoundationTests/Mocks/ICacheDownloaderMock.generated.swift
Tests/FoundationTests/Mocks/IReachabilityCheckerMock.generated.swift
Tests/RugbyTests/Commands/Basic/WarmupTests.swift

You can find a description in #329.
```sh
> rugby warmup "some_binaries_endpoint" --headers "X-JFrog-Art-Api: my-api-key"
```

🚀 Implement ability to add headers in warmup command

---

.github/scripts/update_docs.rb
Docs/commands-help/README.md
Makefile

I've added a script to update the documentation.
```sh
> ruby .github/scripts/update_docs.rb
```
```sh
> make docs
```

⚙️ Added script to update docs

---

Docs/commands-help/shortcuts/cache.md
Sources/Rugby/Commands/Mixed/Shortcuts.swift
Sources/Rugby/Core/Help/HelpPrinter.swift
Sources/RugbyFoundation/XcodeProject/Services/XcodeTargetsEditor.swift

- I've sped up deleting sources in the multi-proj configuration up to 10x
- I've fixed the help output width
- I've implemented an ability to add warmup headers in the `cache` command

🏎️  Speed up the process of deleting sources

---

.github/workflows/checks.yml
Sources/RugbyFoundation/Core/Build/XcodeBuild/XcodeBuildExecutor.swift

- I've added creating a simlink to the latest logs folder;
- That should be useful to beautify `rawBuild.log` after using the `rugby build` command.
```yml
- name: Beautify logs
if: always()
run: cat ~/.rugby/logs/+latest/rawBuild.log 2>&1 | xcbeautify --renderer github-actions
```
| Messages in a pull request changes |
| ------------- |
| <img width="604" alt="Screenshot 2024-03-15 at 20 16 09" src="https://github.com/swiftyfinch/Rugby/assets/64660122/e07a2fc5-a7d4-47c5-91d3-31c7737dc212">  |
| <img width="738" alt="Screenshot 2024-03-15 at 20 16 18" src="https://github.com/swiftyfinch/Rugby/assets/64660122/af82feb7-7dde-4126-afc6-62514a020d30"> |
- #357

⚙️ Creating a simlink to the latest logs folder

---

Sources/RugbyFoundation/Core/Build/BuildTargetsManager.swift
Sources/RugbyFoundation/Core/Use/UseBinariesManager.swift
Sources/RugbyFoundation/Core/Use/XCFrameworksPatcher.swift
Sources/RugbyFoundation/Vault/Commands/Vault+Use.swift
Sources/RugbyFoundation/XcodeProject/Services/XcodeBuildConfigurationEditor.swift
Sources/RugbyFoundation/XcodeProject/Services/XcodePhaseEditor.swift
Sources/RugbyFoundation/XcodeProject/Services/XcodeTargetsEditor.swift
Sources/RugbyFoundation/XcodeProject/XcodeProject.swift
Tests/FoundationTests/Core/Build/BuildTargetsManagerTests.swift
Tests/FoundationTests/Core/Use/UseBinariesManagerTests.swift
Tests/FoundationTests/Core/Use/XCFrameworksPatcherTests.swift
Tests/FoundationTests/Mocks/IInternalXcodeProjectMock.generated.swift
Tests/FoundationTests/Mocks/IXCFrameworksPatcherMock.generated.swift
Tests/FoundationTests/Mocks/IXcodeBuildConfigurationEditorMock.generated.swift
Tests/FoundationTests/Mocks/IXcodePhaseEditorMock.generated.swift
Tests/FoundationTests/Mocks/Mocks.swift
Tests/FoundationTests/XcodeProject/Services/XcodeBuildConfigurationEditorTests.swift
Tests/FoundationTests/XcodeProject/Services/XcodePhaseEditorTests.swift

> The problem occurs when using the "XCFramework" script phase in combination with the "sources" phase.
We need to separate the "XCFramework" script phase from the built target to create a separate aggregate target.
These changes allow us to use podspec files with:
```ruby
s.vendored_frameworks = "Some.xcframework"
s.source_files        = 'Sources/SomePod/**/*.swift'
```
- #382 

🚀 Added detaching XCFramework phase to separate target

---

Sources/Rugby/Core/Dependencies/Update/GitHubReleaseListLoader.swift

This PR improves messaging for errors in the 4XX range when updating Rugby version directly from Github.
It is related to the issue I report in this discussion: https://github.com/swiftyfinch/Rugby/discussions/386
Before these changes, the output looked like:
```
⚑ Update
◑ [0s] Loading Releases
⛔️ Error: typeMismatch(Swift.Array<Any>, Swift.DecodingError.Context(codingPath: [], debugDescription: "Expected to decode Array<Any> but found a dictionary instead.", underlyingError: nil))
```
With these changes, the output looks like:
```
rugby update
⚑ Update
⚑ Loading Releases
⛔️ Error: API rate limit exceeded for XXX.XXX.XXX.XXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
``` …

🚀 Improve 4XX error message management

---

Sources/Rugby/Core/Dependencies/Update/GitHubReleaseListLoader.swift
Sources/Rugby/Core/Dependencies/Update/GitHubUpdater.swift

Due to API rate limits, which allow **only 60 requests per hour**, I have added another way to avoid these restrictions.
I use the link to the latest release to find the latest tag name, and then we can download the binary directly without making any API calls.
Also, I have shortened the error message and added a helpful hint:
- https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api
- https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases
- #386
- #387 

🚀 Add ability to load latest release without api request

---

Sources/RugbyFoundation/Core/Env/EnvironmentCollector.swift
Sources/RugbyFoundation/Core/Env/XcodeCLTVersionProvider.swift
Tests/FoundationTests/Core/Env/EnvironmentCollectorTests.swift
Tests/FoundationTests/Core/Env/XcodeCLTVersionProviderTests.swift

I have changed the format of the Xcode base and the build versions.
```yml
xcode_version: Xcode 15.0.1 (Build version 15A507)
```
```yml
xcode_version: 15.0.1 (15A507)
```
- #395 

Change format of xcode version

---

Sources/RugbyFoundation/Core/Test/TestplanEditor.swift
Tests/FoundationTests/Core/Common/Hashers/SHA1HasherTests.swift
Tests/FoundationTests/Core/Test/TestplanEditorTests.swift
Tests/FoundationTests/Core/Warmup/ReachabilityCheckerTests.swift

- https://github.com/realm/SwiftLint/issues/5263

⚙️ Lint by new rule `non_optional_string_data_conversion`

---

Sources/RugbyFoundation/Core/Build/XcodeBuild/XcodeBuild.swift
Sources/RugbyFoundation/Core/Common/Hashers/TargetsHasher.swift
Sources/RugbyFoundation/Core/Env/EnvironmentCollector.swift
Sources/RugbyFoundation/Core/Use/SupportFilesPatcher.swift
Sources/RugbyFoundation/XcodeProject/Services/XcodeProjectDataSource.swift
Tests/FoundationTests/Core/Use/SupportFilesPatcherTests.swift

- Fixed issue with search header paths not ending with "Headers".
- Replaced incorrect usage of `map` with `flatMap` to resolve mapping error.
- ${PODS_CONFIGURATION_BUILD_DIR}/ReactCommon/ReactCommon.framework/Headers/react/nativemodule/core not changed to rugby
https://github.com/facebook/react-native/blob/7278ff01d7a48607f67079ca4a4e435e3b7125bf/packages/react-native/React/CoreModules/React-CoreModules.podspec#L75

Fix: Handle cases where search header path does not end with "Headers"

---

.github/workflows/checks.yml
.github/workflows/release.yml
Example/Tests/cache_tests.sh
Example/Tests/cache_tests_multiproj.sh
Sources/Rugby/Commands/Basic/Build/BuildOptions.swift
Sources/Rugby/Commands/Basic/Warmup.swift
Sources/Rugby/Utils/Logger/Printers/ProgressPrinter.swift

- https://github.com/swiftlang/swift-evolution/blob/main/proposals/0364-retroactive-conformance-warning.md
- https://github.com/swiftlang/swift-evolution/blob/main/proposals/0306-actors.md
- https://github.com/actions/runner-images/blob/main/images/macos/macos-15-arm64-Readme.md

⚠️ Fix Xcode 16 Warnings

---

Example/Tests/cache_tests.sh
Sources/RugbyFoundation/Core/Build/XcodeBuild/XCARGSProvider.swift
Tests/FoundationTests/Core/Build/XcodeBuild/XcodeBuildTests.swift
Tests/FoundationTests/Core/Common/Hashers/ConfigurationsHasherTests.swift
Tests/FoundationTests/Core/Common/Hashers/TargetsHasherTests.swift
Tests/FoundationTests/Core/Test/TestImpactManagerTests.swift
Tests/FoundationTests/Core/Test/TestsStorageTests.swift

It seems that the root of the problem lies in the use of `SWIFT_COMPILATION_MODE=wholemodule` as the default setting for `xcodebuild`. While this flag was initially introduced to optimize build times, I believe that prioritizing stability is more important at this point.
- #452 

Fix build on Xcode 16.3

---

.github/dependabot.yml

This pull request updates the `.github/dependabot.yml` configuration to exclude the PLzmaSDK dependency from regular updates by Dependabot. The change ensures that Dependabot does not attempt to update this dependency, avoiding potential issues caused by unsafe flags or compatibility concerns.
```sh
error: 'repo': the target 'libplzma' in product 'PLzmaSDK' contains unsafe build flags
```
- https://github.com/OlehKulykov/PLzmaSDK/blob/master/Package.swift#L21

🤖 Exclude PLzmaSDK from Dependabot updates
